//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPower.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Dictionary
    {
        public Base_Dictionary()
        {
            this.Base_Dictionary_Value = new HashSet<Base_Dictionary_Value>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Creater { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Base_Dictionary_Value> Base_Dictionary_Value { get; set; }
    }
}
