//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPower.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPowerConStr : DbContext
    {
        public MyPowerConStr()
            : base("name=MyPowerConStr")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base_Buttons> Base_Buttons { get; set; }
        public virtual DbSet<Base_Department> Base_Department { get; set; }
        public virtual DbSet<Base_log> Base_log { get; set; }
        public virtual DbSet<Base_Login_log> Base_Login_log { get; set; }
        public virtual DbSet<Base_Recyclebin> Base_Recyclebin { get; set; }
        public virtual DbSet<Base_Recyclebin_dataSource> Base_Recyclebin_dataSource { get; set; }
        public virtual DbSet<Base_Role> Base_Role { get; set; }
        public virtual DbSet<Base_UserGroup> Base_UserGroup { get; set; }
        public virtual DbSet<Base_Usr> Base_Usr { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<Base_Dictionary> Base_Dictionary { get; set; }
        public virtual DbSet<Base_Dictionary_Value> Base_Dictionary_Value { get; set; }
    }
}
